In [8]:
# import the usual libraries
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

# for cleaning
import datetime

In [9]:
# read in file of dengue cases with trends
trends = pd.read_csv('../../assets/google_trends.csv')

In [10]:
trends.head()

,Week,dengue: (Singapore),Dengue fever: (Singapore),dengue symptoms: (Singapore),rashes: (Singapore),vomiting: (Singapore),eye pain: (Singapore),joint pain: (Singapore),fever: (Singapore),Wolbachia: (Singapore),headache: (Singapore),nausea: (Singapore),Fogging: (Singapore),Insect repellent: (Singapore),Mosquito: (Singapore)
0,5/1/14,44,61,18,67,43,30,27,73,0,22,9,0,1,5
1,12/1/14,38,55,14,73,38,0,26,66,2,25,11,0,3,5
2,19/1/14,31,46,13,60,52,12,13,80,0,27,8,0,3,4
3,26/1/14,23,33,8,57,39,31,0,64,0,25,12,0,3,6
4,2/2/14,28,38,6,56,31,0,7,72,0,22,8,0,3,8

In [11]:
# check format of series
trends.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 15 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Week                           261 non-null    object
 1   dengue: (Singapore)            261 non-null    int64
 2   Dengue fever: (Singapore)      261 non-null    int64
 3   dengue symptoms: (Singapore)   261 non-null    int64
 4   rashes: (Singapore)            261 non-null    int64
 5   vomiting: (Singapore)          261 non-null    int64
 6   eye pain: (Singapore)          261 non-null    int64
 7   joint pain: (Singapore)        261 non-null    int64
 8   fever: (Singapore)             261 non-null    int64
 9   Wolbachia: (Singapore)         261 non-null    int64
 10  headache: (Singapore)          261 non-null    int64
 11  nausea: (Singapore)            261 non-null    int64
 12  Fogging: (Singapore)           261 non-null    int64
 13  Insect repellent: (Singapore)  261 non-null    int64
 14  Mosquito: (Singapore)          261 non-null    int64
dtypes: int64(14), object(1)
memory usage: 30.7+ KB

In [13]:
# convert to datetime format
trends['date']=pd.to_datetime(trends['Week'], format='%d/%m/%y')

# split into year, month, and week
trends['year'] = trends['date'].dt.year
trends['month'] = trends['date'].dt.month
trends['week'] = trends['date'].dt.week # convert to weeks 1 to 52

/var/folders/t4/n89gfp4s10b4j476kq4xh2p00000gn/T/ipykernel_10621/126485608.py:7: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  trends['week'] = trends['date'].dt.week # convert to weeks 1 to 52

In [14]:
# check the data
trends.head()

,Week,dengue: (Singapore),Dengue fever: (Singapore),dengue symptoms: (Singapore),rashes: (Singapore),vomiting: (Singapore),eye pain: (Singapore),joint pain: (Singapore),fever: (Singapore),Wolbachia: (Singapore),headache: (Singapore),nausea: (Singapore),Fogging: (Singapore),Insect repellent: (Singapore),Mosquito: (Singapore),date,year,month,week
0,5/1/14,44,61,18,67,43,30,27,73,0,22,9,0,1,5,2014-01-05,2014,1,1
1,12/1/14,38,55,14,73,38,0,26,66,2,25,11,0,3,5,2014-01-12,2014,1,2
2,19/1/14,31,46,13,60,52,12,13,80,0,27,8,0,3,4,2014-01-19,2014,1,3
3,26/1/14,23,33,8,57,39,31,0,64,0,25,12,0,3,6,2014-01-26,2014,1,4
4,2/2/14,28,38,6,56,31,0,7,72,0,22,8,0,3,8,2014-02-02,2014,2,5

In [15]:
trends.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Week                           261 non-null    object
 1   dengue: (Singapore)            261 non-null    int64
 2   Dengue fever: (Singapore)      261 non-null    int64
 3   dengue symptoms: (Singapore)   261 non-null    int64
 4   rashes: (Singapore)            261 non-null    int64
 5   vomiting: (Singapore)          261 non-null    int64
 6   eye pain: (Singapore)          261 non-null    int64
 7   joint pain: (Singapore)        261 non-null    int64
 8   fever: (Singapore)             261 non-null    int64
 9   Wolbachia: (Singapore)         261 non-null    int64
 10  headache: (Singapore)          261 non-null    int64
 11  nausea: (Singapore)            261 non-null    int64
 12  Fogging: (Singapore)           261 non-null    int64
 13  Insect repellent: (Singapore)  261 non-null    int64
 14  Mosquito: (Singapore)          261 non-null    int64
 15  date                           261 non-null    datetime64[ns]
 16  year                           261 non-null    int64
 17  month                          261 non-null    int64
 18  week                           261 non-null    int64
dtypes: datetime64[ns](1), int64(17), object(1)
memory usage: 38.9+ KB

In [16]:
# rename the columns
new_columns_dict = {
    'dengue: (Singapore)': 'dengue_search',
    'Dengue fever: (Singapore)': 'dengue_fever_search',
    'dengue symptoms: (Singapore)': 'dengue_symptoms_search',
    'rashes: (Singapore)': 'rashes_search',
    'vomiting: (Singapore)': 'vomiting_search',
    'eye pain: (Singapore)': 'eye_pain_search',
    'joint pain: (Singapore)': 'joint_pain_search',
    'fever: (Singapore)': 'fever_search',
    'Wolbachia: (Singapore)': 'wolbachia_search',
    'headache: (Singapore)': 'headache_search',
    'nausea: (Singapore)': 'nausea_search',
    'Fogging: (Singapore)': 'fogging_search',
    'Insect repellent: (Singapore)': 'insect_repellent_search',
    'Mosquito: (Singapore)' : 'mosquito_search'
}

# assign new column names
trends.rename(columns = new_columns_dict, inplace=True)

In [17]:
# reassign the column names
trends_columns = ['date', 'year', 'month', 'week', 'dengue_search', 'dengue_fever_search','dengue_symptoms_search',  
                  'rashes_search', 'vomiting_search', 'eye_pain_search', 'joint_pain_search',
                 'fever_search', 'wolbachia_search', 'headache_search', 'nausea_search', 'fogging_search',
                 'insect_repellent_search','mosquito_search']

trends = trends[trends_columns]

In [18]:
# check if all headers are aligned
trends.head()

,date,year,month,week,dengue_search,dengue_fever_search,dengue_symptoms_search,rashes_search,vomiting_search,eye_pain_search,joint_pain_search,fever_search,wolbachia_search,headache_search,nausea_search,fogging_search,insect_repellent_search,mosquito_search
0,2014-01-05,2014,1,1,44,61,18,67,43,30,27,73,0,22,9,0,1,5
1,2014-01-12,2014,1,2,38,55,14,73,38,0,26,66,2,25,11,0,3,5
2,2014-01-19,2014,1,3,31,46,13,60,52,12,13,80,0,27,8,0,3,4
3,2014-01-26,2014,1,4,23,33,8,57,39,31,0,64,0,25,12,0,3,6
4,2014-02-02,2014,2,5,28,38,6,56,31,0,7,72,0,22,8,0,3,8

In [19]:
trends.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     261 non-null    datetime64[ns]
 1   year                     261 non-null    int64
 2   month                    261 non-null    int64
 3   week                     261 non-null    int64
 4   dengue_search            261 non-null    int64
 5   dengue_fever_search      261 non-null    int64
 6   dengue_symptoms_search   261 non-null    int64
 7   rashes_search            261 non-null    int64
 8   vomiting_search          261 non-null    int64
 9   eye_pain_search          261 non-null    int64
 10  joint_pain_search        261 non-null    int64
 11  fever_search             261 non-null    int64
 12  wolbachia_search         261 non-null    int64
 13  headache_search          261 non-null    int64
 14  nausea_search            261 non-null    int64
 15  fogging_search           261 non-null    int64
 16  insect_repellent_search  261 non-null    int64
 17  mosquito_search          261 non-null    int64
dtypes: datetime64[ns](1), int64(17)
memory usage: 36.8 KB

In [20]:
# Define a function to add one day to a datetime object
def add_one_day(date):
    new_date = date + datetime.timedelta(days=1)
    new_date = new_date.strftime('%Y-%d-%m')
    return new_date

In [21]:
# Apply the function to the 'date' column
trends['date'] = trends['date'].apply(add_one_day)

/var/folders/t4/n89gfp4s10b4j476kq4xh2p00000gn/T/ipykernel_10621/2715865963.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trends['date'] = trends['date'].apply(add_one_day)

In [22]:
trends.head(10)

,date,year,month,week,dengue_search,dengue_fever_search,dengue_symptoms_search,rashes_search,vomiting_search,eye_pain_search,joint_pain_search,fever_search,wolbachia_search,headache_search,nausea_search,fogging_search,insect_repellent_search,mosquito_search
0,2014-06-01,2014,1,1,44,61,18,67,43,30,27,73,0,22,9,0,1,5
1,2014-13-01,2014,1,2,38,55,14,73,38,0,26,66,2,25,11,0,3,5
2,2014-20-01,2014,1,3,31,46,13,60,52,12,13,80,0,27,8,0,3,4
3,2014-27-01,2014,1,4,23,33,8,57,39,31,0,64,0,25,12,0,3,6
4,2014-03-02,2014,2,5,28,38,6,56,31,0,7,72,0,22,8,0,3,8
5,2014-10-02,2014,2,6,35,50,14,75,56,0,10,58,0,24,15,0,3,13
6,2014-17-02,2014,2,7,28,41,11,55,34,7,12,59,0,25,11,39,4,12
7,2014-24-02,2014,2,8,34,49,16,40,21,0,23,73,0,28,7,18,6,19
8,2014-03-03,2014,3,9,31,54,16,42,30,10,14,56,2,20,10,28,9,20
9,2014-10-03,2014,3,10,18,33,7,62,39,0,18,48,0,14,13,0,6,17

In [23]:
# export the trends dataframe into a .csv file
trends.to_csv('../../assets/complete_google_trends.csv')